AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    SAM Template for lambda
Globals:
    Function:
        Timeout: 4

Resources:

    HelloWorldFunction:
        Type: AWS::Serverless::Function 
        Properties:
            CodeUri:
                Bucket: hidokai
                Key: hello/handler.zip
            Handler: handler.lambda_handler
            Runtime: python3.7
            AutoPublishAlias: live
            
Outputs:
    HelloWorldFunction:
      Description: "Hello World Lambda Function ARN"
      Value: !GetAtt HelloWorldFunction.Arn

    HelloWorldFunctionIamRole:
      Description: "Implicit IAM Role created for Hello World function"
      Value: !GetAtt HelloWorldFunctionRole.Arn
